default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: folio_rails_development

test:
  <<: *default
  database: folio_rails_test

production:
  <<: *default
  database: folio_rails_production
